package com.example.mynasaapp.Support;


public class Data {

    public static String[] tickers = {
            "SDGR",
            "PLL",
            "LTHM",
            "ASML",
            "DOGE-USD",
            "WNDW",
            "BTC-USD",
            "SANP",
            "SPRQ",
            "SPO.CN",
            "ALB",
            "OSS",
            "CHK",
            "LTNC",
            "ADA-CAD",
            "SHLS",
            "HCMC",
            "BEKE",
            "CCIV",
            "CIIC",
            "PRNT",
            "BFARF",
            "GTEH",
            "AITX",
            "BTC-CAD",
            "SFTW",
            "ETH-EUR",
            "UAL",
            "AABB",
            "MGM",
            "DOGE-CAD",
            "MP",
            "CTRM",
            "FSR",
            "ASTI",
            "NSAV",
            "ACIC",
            "BCH-USD",
            "LMT",
            "EXPC",
            "SMH",
            "CRSP",
            "BLNK",
            "FUTU",
            "BA",
            "NNOX",
            "DMTK",
            "SE",
            "ETH-CAD",
            "SNPR",
            "IVR",
            "RDFN",
            "RYCEY",
            "PSTH",
            "TAAS-USD",
            "PG",
            "CLOV",
            "LTC-USD",
            "MMED.NE",
            "IQST",
            "OXY",
            "MINE",
            "DM",
            "ARKQ",
            "LUMN",
            "NGAC",
            "ALYI",
            "RTX",
            "LAC",
            "JD",
            "NVAX",
            "COST",
            "CRON",
            "MCD",
            "GNUS",
            "SXOOF",
            "UPWK",
            "IPOF",
            "QS",
            "Z",
            "SOXL",
            "JMIA",
            "XLM-USD",
            "GILT",
            "BTC-EUR",
            "NKLA",
            "CBDT.CN",
            "CRM",
            "OZSC",
            "INND",
            "DOC.V",
            "HVBTF",
            "UBER",
            "VTI",
            "LIT",
            "HYLN",
            "GOOG",
            "SOLO",
            "VET-USD",
            "TRCH",
            "CAT",
            "SQ",
            "INO",
            "ARKG",
            "AQMS",
            "XL",
            "IPOE"
    };

    public static String searchTicker(String tick){
        for (String ticker : tickers) {
            if (tick.equals(ticker))
                return ticker;
        }
        return null;
    }
}

